#pragma once
#include "../Common/Def.h"
#include "../Common/Singleton.h"
#include "../Common/CMmdCtrls.h"
#include "../Common/CUnknownChecker.h"
#include "../Common/CInifile.h"
#include "../Common/CKeyState.h"
#include "../Common/CPostMsgHook.h"
#include "../Common/CMenu.h"
